import 'dart:async';

import 'package:bus_services/globals.dart' as globals;

Stream<int> isLoggedin() {
  controller.sink.add(0);
  return controller.stream;
}

final controller = StreamController<int>();

List users = [
  {
    "id": "driver",
    "name": "driver",
    "img": globals.loginBg,
    "phone": "9872435674",
    "pass_word": "123",
  }
];

List buses = [
  {
    "bus_num": "test1",
    "batch": "batch1",
    "timing": "1664379964",
    "students": [
      {
        "id": "1",
        "status": "-1",
      },
      {
        "id": "12",
        "status": "-1",
      },
      {
        "id": "14",
        "status": "-1",
      },
      {
        "id": "16",
        "status": "-1",
      },
      {
        "id": "19",
        "status": "-1",
      },
    ],
  },
  {
    "bus_num": "test2",
    "batch": "batch1",
    "timing": "1662379964",
    "students": [
      {
        "id": "10",
        "status": "-1",
      },
      {
        "id": "15",
        "status": "-1",
      },
      {
        "id": "17",
        "status": "-1",
      },
    ],
  },
  {
    "bus_num": "test3",
    "batch": "batch2",
    "timing": "1666579964",
    "students": [
      {
        "id": "11",
        "status": "-1",
      },
      {
        "id": "13",
        "status": "-1",
      },
      {
        "id": "18",
        "status": "-1",
      },
    ],
  }
];

List students = [
  {
    "DOB": "2022-10-16",
    "Enroll": "",
    "Gr_num": "1",
    "Medium": "Branch-1",
    "Name": "TEST",
    "Section": "A",
    "Std": "junior.kg",
    "active_status": "1",
    "address": "SD",
    "adhar_num": "",
    "area_code": "1",
    "birth_place": "",
    "caste": "OPEN",
    "cont_num": "9028176254",
    "email": "tejal.malusare@bitbluetech.com",
    "f_name": "AA",
    "gcm_id": "-",
    "gender": "male",
    "house": "",
    "m_name": "BB",
    "nationality": "",
    "pass_word": "7050",
    "religion": "",
    "roll_no": "0",
    "session_time": "-",
    "student_img":
        "https://dextro-exam.com/DEXTRO/dextro1920/student_img/sch/1.jpg",
    "whatsapp_no": ""
  },
  {
    "DOB": "2003-05-28",
    "Enroll": "",
    "Gr_num": "10",
    "Medium": "branch-1",
    "Name": "Shaikh Arbaaz Ejaz Ahmed",
    "Section": "A",
    "Std": "second",
    "active_status": "1",
    "address": "64/B3 Highland bldg, Narendra Park, Naya ngr, Mira rd",
    "adhar_num": "No data",
    "area_code": "0",
    "birth_place": "No data",
    "caste": "No data",
    "cont_num": "8451845162",
    "email": "tejal.malusare@bitbluetech.com",
    "f_name": "Ejaz Ahmed",
    "gcm_id": "-",
    "gender": "male",
    "house": "",
    "m_name": "Rozina",
    "nationality": "Indian",
    "pass_word": "0314391",
    "religion": "No data",
    "roll_no": "0",
    "session_time": "-",
    "student_img":
        "https://dextro-exam.com/DEXTRO/dextro1920/student_img/sch/10.jpg",
    "whatsapp_no": ""
  },
  {
    "DOB": "2003-05-28",
    "Enroll": "",
    "Gr_num": "11",
    "Medium": "branch-2",
    "Name": "Shaikh Sahil Shaneali",
    "Section": "A",
    "Std": "second",
    "active_status": "1",
    "address":
        "303/A wing Saryu Sargam, Beside Sita Park, Lodha rdx, Naya nagar Mira rd (E) Thane",
    "adhar_num": "No data",
    "area_code": "0",
    "birth_place": "No data",
    "caste": "No data",
    "cont_num": "8451845162",
    "email": "tejal.malusare@bitbluetech.com",
    "f_name": "Shaneali",
    "gcm_id": "-",
    "gender": "male",
    "house": "",
    "m_name": "Parveen",
    "nationality": "Indian",
    "pass_word": "0770425",
    "religion": "No data",
    "roll_no": "0",
    "session_time": "-",
    "student_img":
        "https://dextro-exam.com/DEXTRO/dextro1920/student_img/sch/11.jpg",
    "whatsapp_no": ""
  },
  {
    "DOB": "2003-06-10",
    "Enroll": "",
    "Gr_num": "12",
    "Medium": "branch-2",
    "Name": "Pujary Pratham Prakash",
    "Section": "A",
    "Std": "second",
    "active_status": "1",
    "address":
        "New Mhada Complex L-2 , 401, Shanti garden, Nr Surya shopping centre, Mira rd",
    "adhar_num": "No data",
    "area_code": "0",
    "birth_place": "No data",
    "caste": "No data",
    "cont_num": "8451845162",
    "email": "tejal.malusare@bitbluetech.com",
    "f_name": "Prakash",
    "gcm_id": "-",
    "gender": "male",
    "house": "",
    "m_name": "Surekha",
    "nationality": "Indian",
    "pass_word": "0908951",
    "religion": "No data",
    "roll_no": "0",
    "session_time": "-",
    "student_img":
        "https://dextro-exam.com/DEXTRO/dextro1920/student_img/sch/12.jpg",
    "whatsapp_no": ""
  },
  {
    "DOB": "2002-08-28",
    "Enroll": "",
    "Gr_num": "13",
    "Medium": "branch-2",
    "Name": "D'souza Chris Shane",
    "Section": "A",
    "Std": "second",
    "active_status": "1",
    "address":
        "801/B wing, Building no 2 RNA Silver Springs , Ram dev Park Mira rd",
    "adhar_num": "No data",
    "area_code": "0",
    "birth_place": "No data",
    "caste": "No data",
    "cont_num": "8451845162",
    "email": "tejal.malusare@bitbluetech.com",
    "f_name": "Shane",
    "gcm_id": "-",
    "gender": "male",
    "house": "",
    "m_name": "Shakuntala",
    "nationality": "Indian",
    "pass_word": "0233482",
    "religion": "No data",
    "roll_no": "0",
    "session_time": "-",
    "student_img":
        "https://dextro-exam.com/DEXTRO/dextro1920/student_img/sch/13.jpg",
    "whatsapp_no": ""
  },
  {
    "DOB": "2004-04-28",
    "Enroll": "30",
    "Gr_num": "14",
    "Medium": "branch-2",
    "Name": "Vibhad Shreya Ajit",
    "Section": "A",
    "Std": "second",
    "active_status": "1",
    "address":
        "G-002,Matoshree Nagar,Nr.Bharti Park,Mira Bhayander Rd.Mira Rd.",
    "adhar_num": "756507349357",
    "area_code": "0",
    "birth_place": "mumbai",
    "caste": "open",
    "cont_num": "8451845162",
    "email": "tejal.malusare@bitbluetech.com",
    "f_name": "Ajit",
    "gcm_id": "-",
    "gender": "female",
    "house": "",
    "m_name": "Poonam",
    "nationality": "Indian",
    "pass_word": "0440559",
    "religion": "hindu",
    "roll_no": "0",
    "session_time": "-",
    "student_img":
        "https://dextro-exam.com/DEXTRO/dextro1920/student_img/sch/14.jpg",
    "whatsapp_no": ""
  },
  {
    "DOB": "2004-11-16",
    "Enroll": "28",
    "Gr_num": "15",
    "Medium": "branch-2",
    "Name": "Shrestha Alisha Rambahadur",
    "Section": "A",
    "Std": "second",
    "active_status": "1",
    "address": "A/603, Sai Charan Residency, Ramdev Park, Mira Rd.",
    "adhar_num": "396795719593",
    "area_code": "0",
    "birth_place": "mumbai",
    "caste": "open",
    "cont_num": "8451845162",
    "email": "tejal.malusare@bitbluetech.com",
    "f_name": "Rambahadur",
    "gcm_id": "-",
    "gender": "female",
    "house": "",
    "m_name": "Sunita",
    "nationality": "Indian",
    "pass_word": "0502346",
    "religion": "hindu",
    "roll_no": "0",
    "session_time": "-",
    "student_img":
        "https://dextro-exam.com/DEXTRO/dextro1920/student_img/sch/15.jpg",
    "whatsapp_no": ""
  },
  {
    "DOB": "2004-12-06",
    "Enroll": "68",
    "Gr_num": "16",
    "Medium": "branch-2",
    "Name": "Sharma Paridhi Dinesh",
    "Section": "A",
    "Std": "first",
    "active_status": "1",
    "address": "B-705, Om Narmada C.H.S,Station Road, Mira Rd.",
    "adhar_num": "812414274415",
    "area_code": "0",
    "birth_place": "Mumbai",
    "caste": "open",
    "cont_num": "8451845162",
    "email": "tejal.malusare@bitbluetech.com",
    "f_name": "Dinesh",
    "gcm_id": "-",
    "gender": "female",
    "house": "",
    "m_name": "Charu",
    "nationality": "Indian",
    "pass_word": "0190057",
    "religion": "Hindu",
    "roll_no": "1",
    "session_time": "-",
    "student_img":
        "https://dextro-exam.com/DEXTRO/dextro1920/student_img/sch/16.jpg",
    "whatsapp_no": ""
  },
  {
    "DOB": "2004-10-10",
    "Enroll": "66",
    "Gr_num": "17",
    "Medium": "branch-2",
    "Name": "Saxena Riddhima Amit",
    "Section": "A",
    "Std": "first",
    "active_status": "1",
    "address": "B-303,LA-Vista Apartment, Poonam Sagar Complex,Mira Rd.",
    "adhar_num": "400708334045",
    "area_code": "0",
    "birth_place": "Lucknow",
    "caste": "open",
    "cont_num": "8451845162",
    "email": "tejal.malusare@bitbluetech.com",
    "f_name": "Amit",
    "gcm_id": "-",
    "gender": "female",
    "house": "",
    "m_name": "Varsha",
    "nationality": "Indian",
    "pass_word": "0443246",
    "religion": "Hindu",
    "roll_no": "4",
    "session_time": "-",
    "student_img":
        "https://dextro-exam.com/DEXTRO/dextro1920/student_img/sch/17.jpg",
    "whatsapp_no": ""
  },
  {
    "DOB": "2004-04-10",
    "Enroll": "62",
    "Gr_num": "18",
    "Medium": "branch-2",
    "Name": "SANIL URVI VIJITHENDRA",
    "Section": "A",
    "Std": "first",
    "active_status": "1",
    "address":
        "A3001 Unity Apartment Near bharti park Mira Road East. Pin 401107",
    "adhar_num": "359672375200",
    "area_code": "0",
    "birth_place": "Mumbai",
    "caste": "No data",
    "cont_num": "8451845162",
    "email": "tejal.malusare@bitbluetech.com",
    "f_name": "VIJITHENDRA",
    "gcm_id": "-",
    "gender": "female",
    "house": "",
    "m_name": "RESHMA",
    "nationality": "Indian",
    "pass_word": "0646061",
    "religion": "Hindu",
    "roll_no": "5",
    "session_time": "-",
    "student_img":
        "https://dextro-exam.com/DEXTRO/dextro1920/student_img/sch/18.jpg",
    "whatsapp_no": ""
  },
  {
    "DOB": "2004-03-12",
    "Enroll": "63",
    "Gr_num": "19",
    "Medium": "branch-2",
    "Name": "Rangari Sinin Mohd. Salim",
    "Section": "A",
    "Std": "nursery",
    "active_status": "1",
    "address": "4 A/101 Asmita Anita Complex , Naya Nagar Mira Rd.",
    "adhar_num": "850268052875",
    "area_code": "0",
    "birth_place": "Mumbai",
    "caste": "open",
    "cont_num": "8451845162",
    "email": "tejal.malusare@bitbluetech.com",
    "f_name": "Mohd. Salim",
    "gcm_id": "-",
    "gender": "female",
    "house": "",
    "m_name": "Farzana",
    "nationality": "Indian",
    "pass_word": "0900568",
    "religion": "Muslim",
    "roll_no": "0",
    "session_time": "-",
    "student_img":
        "https://dextro-exam.com/DEXTRO/dextro1920/student_img/sch/19.jpg",
    "whatsapp_no": ""
  }
];
